### ISSUE TITLE
Support multiple values in attributes.

### ISSUE THREAD

**Issue by kremovtort** [typeable/xml-isogen#21]
Now `xml-isogen` attributes that contents only one value. 

It common pattern for xml to contain multiple values in attribute splitted by space.

I suggest to add 2 operators: `+%` and `*%` for parsing/encoding lists in attributes.

For example:
```haskell
"tname" =:= record
  *% "aname" [t|Int|]
```

```xml
<tname aname="1 2 15" />
```
will be parsed to 
```haskell
XmlTname { _xtAname = [1, 2, 15] }
```

**Comment by dredozubov** [comment]
I'm not quite sure if it's an xml feature or application-level specifics you've encountered. Could you please link the XML spec related to this feature of attributes?

**Comment by kremovtort** [comment]
> I'm not quite sure if it's an xml feature or application-level specifics you've encountered. Could you please link the XML spec related to this feature of attributes?

@dredozubov, in XSD we can define [`attribute`](https://www.w3schools.com/xml/el_attribute.asp) with any [`simpleType`](https://www.w3schools.com/xml/el_simpletype.asp) as type of content. `simpleType` may be defined as [`list`](https://www.w3schools.com/xml/el_list.asp) of values separated by space.

**Comment by dredozubov** [comment]
I'm convinced! Would you be willing to work on the patch?

**Comment by kremovtort** [comment]
@dredozubov yes.

**Comment by s9gf4ult** [comment]
I would implement this feature in differently.

Instead of adding a new syntax I would add a newtype wrapper with instances 

```haskell
newtype AttrList a = AttrList [a]

instance FromAttribute a => FromAttribute (AttrList a) ...

instance ToXmlAttribute a => ToXmlAttribute (AttrList a) ...
```

So one could just 

```haskell
"tname" =:= record
  !% "aname" [t|AttrList Int|]
```

Because this is more haskell way.

You also can add your own wrappers with semantics you like.
